version: '3'

services:
  db:
    image: postgres
    volumes:
    - ./pgsql-data:/var/lib/pgsql
    env_file:
      - .env
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env